# Generated by Django 5.1.4 on 2024-12-19 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_progress_lesson_alter_progress_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='learning_le_course__30756f_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['user', 'lesson'], name='learning_pr_user_id_0c2863_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['lesson', 'completed'], name='learning_pr_lesson__bc8825_idx'),
        ),
    ]
